apiVersion: v1
kind: Service
metadata:
  name: telegraf-config-manager-access
  namespace: telegraf-config-mgr
  labels:
    app: telegraf-config-manager
  annotations:
    service.beta.kubernetes.io/load-balancer-source-ranges: "192.168.0.0/24"
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.0.13
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: telegraf-config-manager
