apiVersion: v1
kind: Service
metadata:
  name: telegraf-config-manager-service
  namespace: telegraf-config-mgr
  labels:
    app: telegraf-config-manager
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: telegraf-config-manager
